[package]
name = "sophia-backend-live"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
sophia-engine = { path = "../sophia-engine" }
sophia-protocol = { path = "../sophia-protocol" }
sophia-renderer-live = { path = "../sophia-renderer-live" }
sophia-drm-out-fence = { path = "../sophia-drm-out-fence", optional = true }
drm = { version = "0.15", optional = true, default-features = false }
input = { version = "0.10", optional = true, default-features = false, features = ["libinput_1_19", "udev"] }
libseat = { version = "0.2.4", optional = true, default-features = false }
rustix = { version = "1.1", optional = true, default-features = false, features = ["event", "fs", "std", "time"] }
udev = { version = "0.9.3", optional = true }
tracing.workspace = true

[dev-dependencies]
drm-ffi = "0.9.1"
sophia-runtime = { path = "../sophia-runtime" }
sophia-xshmfence = { path = "../sophia-xshmfence" }

[features]
default = []
gbm-probe = ["sophia-renderer-live/gbm-probe"]
egl-probe = ["sophia-renderer-live/egl-probe"]
libdrm-events = ["dep:drm", "dep:rustix", "dep:sophia-drm-out-fence"]
drm-hotplug = ["dep:rustix", "dep:udev"]
libinput-events = ["dep:input", "dep:rustix"]
seat-control = ["dep:libseat", "dep:rustix"]

[lints]
workspace = true
