// Routing the pointer's own position again after a hierarchy change, so
// the crossings a map, unmap, destroy, configure or restack under the
// pointer owes are generated by every writer from its own view (t211).

#[cfg(unix)]
impl XServerFrontendRouteRegistry {
    /// The pointer's position routed again with the crossing a grab owes:
    /// its activation crosses from the pointer window to the grab window
    /// with NotifyGrab, its end back with NotifyUngrab, and every client
    /// selecting crossings on the path is told, as the reference's
    /// DoEnterLeaveEvents has it. A crossing no motion consumed is dropped.
    pub(crate) fn replay_grab_crossing(
        &self,
        namespace: NamespaceId,
        target_surface: SurfaceId,
        global: sophia_protocol::Point,
        local: sophia_protocol::Point,
        crossing: crate::XPointerGrabCrossing,
    ) -> Result<(), XServerFrontendRouteError> {
        self.pending_grab_crossing
            .lock()
            .map_err(|_| XServerFrontendRouteError::RegistryPoisoned)?
            .insert(namespace, crossing);
        let result = self.replay_pointer(namespace, target_surface, global, local);
        self.pending_grab_crossing
            .lock()
            .map_err(|_| XServerFrontendRouteError::RegistryPoisoned)?
            .remove(&namespace);
        result
    }

    /// Route a motion of no distance at the pointer's position, to the
    /// surface now under it: each writer re-derives the window the pointer
    /// is in and writes the crossings from where it was, and a motion that
    /// moved nothing is written to nobody as MotionNotify. Sent as the seat
    /// and device the pointer last arrived on; where none has, nothing has
    /// changed under it. Routed on the caller's thread rather than through
    /// the broker's queue, so that when this returns the event is in every
    /// writer's queue and the caller can wait for its own to drain before
    /// it answers another request.
    pub(crate) fn replay_pointer(
        &self,
        namespace: NamespaceId,
        target_surface: SurfaceId,
        global: sophia_protocol::Point,
        local: sophia_protocol::Point,
    ) -> Result<(), XServerFrontendRouteError> {
        let Some(sender) = self.pointer_replay.get() else {
            return Ok(());
        };
        let memory = self
            .last_pointer_route
            .lock()
            .map_err(|_| XServerFrontendRouteError::RegistryPoisoned)?
            .get(&namespace)
            .copied();
        let Some(memory) = memory else {
            return Ok(());
        };
        let serial = self
            .replay_serial
            .fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        let route = XAuthorityRoutedInput {
            request: sophia_protocol::RoutedInputRequest {
                serial,
                seat: memory.seat,
                device: memory.device,
                time_msec: u64::from(x11_server_time_msec()),
                target_surface,
                global_position: global,
                local_position: local,
                kind: InputEventKind::PointerMotion,
            },
            route_lease: None,
            delivery: None,
            mode: XAuthorityRoutedInputMode::Deliver,
            origin: XAuthorityRoutedInputOrigin::Synthetic,
        };
        let Ok(stamp) = sender.stamp() else {
            // A control transition in flight: nothing is routed against a
            // revision being replaced, and the crossing waits for the next
            // motion.
            return Ok(());
        };
        let admitted = match sender.control_gate.get() {
            Some(gate) => gate.admits(stamp).is_ok(),
            None => true,
        };
        match self.route_engine_input_admitted(route, stamp, admitted) {
            Ok(())
            | Err(
                XServerFrontendRouteError::UnknownSurface { .. }
                | XServerFrontendRouteError::ClientQueueDisconnected { .. }
                | XServerFrontendRouteError::UnknownClient { .. }
                | XServerFrontendRouteError::ClientQueueFull { .. },
            ) => Ok(()),
            Err(error) => Err(error),
        }
    }
}
