// @generated by sophia-policy-protocol-gen; do not edit.
// Source: protocol/sophia-wm-v1.kdl

use super::cursor::{Cursor, push_i32, push_u16, push_u32, push_u64};
use super::frame::{decode_frame, encode_frame};
use super::types::{IpcCodecError, IpcMessageKind};
use crate::TransactionId;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ClientHello {
    pub minimum_revision: u16,
    pub maximum_revision: u16,
    pub capabilities: u64,
}

pub fn encode_wm_v1_client_hello_frame(
    message: &WmV1ClientHello,
) -> Result<Vec<u8>, IpcCodecError> {
    let mut payload = Vec::new();
    push_u16(&mut payload, message.minimum_revision);
    push_u16(&mut payload, message.maximum_revision);
    push_u64(&mut payload, message.capabilities);
    encode_frame(
        IpcMessageKind::WmV1ClientHello,
        TransactionId::INVALID,
        &payload,
    )
}

pub fn decode_wm_v1_client_hello_frame(frame: &[u8]) -> Result<WmV1ClientHello, IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ClientHello {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(header.transaction.raw()));
    }
    let mut cursor = Cursor::new(payload);
    let minimum_revision = cursor.u16()?;
    let maximum_revision = cursor.u16()?;
    let capabilities = cursor.u64()?;
    cursor.finish()?;
    let message = WmV1ClientHello {
        minimum_revision,
        maximum_revision,
        capabilities,
    };
    Ok(message)
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ServerWelcome {
    pub selected_revision: u16,
    pub capabilities: u64,
    pub connection_epoch: u64,
    pub max_outputs: u16,
    pub max_bindings: u16,
    pub max_surfaces: u32,
    pub max_chunk_bytes: u32,
}

pub fn encode_wm_v1_server_welcome_frame(
    message: &WmV1ServerWelcome,
) -> Result<Vec<u8>, IpcCodecError> {
    let mut payload = Vec::new();
    push_u16(&mut payload, message.selected_revision);
    push_u16(&mut payload, 0);
    push_u64(&mut payload, message.capabilities);
    push_u64(&mut payload, message.connection_epoch);
    push_u16(&mut payload, message.max_outputs);
    push_u16(&mut payload, message.max_bindings);
    push_u32(&mut payload, message.max_surfaces);
    push_u32(&mut payload, message.max_chunk_bytes);
    encode_frame(
        IpcMessageKind::WmV1ServerWelcome,
        TransactionId::INVALID,
        &payload,
    )
}

pub fn decode_wm_v1_server_welcome_frame(frame: &[u8]) -> Result<WmV1ServerWelcome, IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ServerWelcome {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(header.transaction.raw()));
    }
    let mut cursor = Cursor::new(payload);
    let selected_revision = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    let capabilities = cursor.u64()?;
    let connection_epoch = cursor.u64()?;
    let max_outputs = cursor.u16()?;
    let max_bindings = cursor.u16()?;
    let max_surfaces = cursor.u32()?;
    let max_chunk_bytes = cursor.u32()?;
    cursor.finish()?;
    let message = WmV1ServerWelcome {
        selected_revision,
        capabilities,
        connection_epoch,
        max_outputs,
        max_bindings,
        max_surfaces,
        max_chunk_bytes,
    };
    Ok(message)
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SnapshotBegin {
    pub connection_epoch: u64,
    pub scene_generation: u64,
    pub active_output: u64,
    pub chunk_count: u16,
    pub output_count: u16,
    pub surface_count: u32,
    pub action_count: u16,
    pub session_operation_count: u16,
}

pub fn encode_wm_v1_snapshot_begin_frame(
    transaction: TransactionId,
    message: &WmV1SnapshotBegin,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.scene_generation);
    push_u64(&mut payload, message.active_output);
    push_u16(&mut payload, message.chunk_count);
    push_u16(&mut payload, message.output_count);
    push_u32(&mut payload, message.surface_count);
    push_u16(&mut payload, message.action_count);
    push_u16(&mut payload, message.session_operation_count);
    encode_frame(IpcMessageKind::WmV1SnapshotBegin, transaction, &payload)
}

pub fn decode_wm_v1_snapshot_begin_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1SnapshotBegin), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1SnapshotBegin {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let scene_generation = cursor.u64()?;
    let active_output = cursor.u64()?;
    let chunk_count = cursor.u16()?;
    let output_count = cursor.u16()?;
    let surface_count = cursor.u32()?;
    let action_count = cursor.u16()?;
    let session_operation_count = cursor.u16()?;
    cursor.finish()?;
    let message = WmV1SnapshotBegin {
        connection_epoch,
        scene_generation,
        active_output,
        chunk_count,
        output_count,
        surface_count,
        action_count,
        session_operation_count,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SnapshotChunk {
    pub connection_epoch: u64,
    pub ordinal: u16,
    pub record_kind: u16,
    pub item_count: u32,
    pub data: Vec<u8>,
}

pub fn encode_wm_v1_snapshot_chunk_frame(
    transaction: TransactionId,
    message: &WmV1SnapshotChunk,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    if message.data.len() > 65520 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "data",
            len: message.data.len(),
            max: 65520,
        });
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u16(&mut payload, message.ordinal);
    push_u16(&mut payload, message.record_kind);
    push_u32(&mut payload, message.item_count);
    payload.extend_from_slice(&message.data);
    encode_frame(IpcMessageKind::WmV1SnapshotChunk, transaction, &payload)
}

pub fn decode_wm_v1_snapshot_chunk_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1SnapshotChunk), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1SnapshotChunk {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let ordinal = cursor.u16()?;
    let record_kind = cursor.u16()?;
    let item_count = cursor.u32()?;
    let len = payload.len().saturating_sub(16);
    if len > 65520 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "data",
            len,
            max: 65520,
        });
    }
    let data = cursor.slice(len)?.to_vec();
    cursor.finish()?;
    let message = WmV1SnapshotChunk {
        connection_epoch,
        ordinal,
        record_kind,
        item_count,
        data,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SnapshotEnd {
    pub connection_epoch: u64,
    pub scene_generation: u64,
    pub chunk_count: u16,
}

pub fn encode_wm_v1_snapshot_end_frame(
    transaction: TransactionId,
    message: &WmV1SnapshotEnd,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.scene_generation);
    push_u16(&mut payload, message.chunk_count);
    push_u16(&mut payload, 0);
    encode_frame(IpcMessageKind::WmV1SnapshotEnd, transaction, &payload)
}

pub fn decode_wm_v1_snapshot_end_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1SnapshotEnd), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1SnapshotEnd {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let scene_generation = cursor.u64()?;
    let chunk_count = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    cursor.finish()?;
    let message = WmV1SnapshotEnd {
        connection_epoch,
        scene_generation,
        chunk_count,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionRequest {
    pub connection_epoch: u64,
    pub request_id: u64,
    pub scene_generation: u64,
    pub policy_generation: u64,
    pub cause_kind: u16,
    pub interaction_phase: u16,
    pub interaction_kind: u16,
    pub interaction_axis: u16,
    pub activation_serial: u64,
    pub action: u64,
    pub target_index: u32,
    pub target_generation: u32,
    pub interaction_x: i32,
    pub interaction_y: i32,
    pub interaction_width: i32,
    pub interaction_height: i32,
    pub affected_output_count: u16,
    pub affected_outputs: Vec<u8>,
}

pub fn encode_wm_v1_projection_request_frame(
    transaction: TransactionId,
    message: &WmV1ProjectionRequest,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    if message.affected_outputs.len() > 128 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "affected_outputs",
            len: message.affected_outputs.len(),
            max: 128,
        });
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.request_id);
    push_u64(&mut payload, message.scene_generation);
    push_u64(&mut payload, message.policy_generation);
    push_u16(&mut payload, message.cause_kind);
    push_u16(&mut payload, message.interaction_phase);
    push_u16(&mut payload, message.interaction_kind);
    push_u16(&mut payload, message.interaction_axis);
    push_u64(&mut payload, message.activation_serial);
    push_u64(&mut payload, message.action);
    push_u32(&mut payload, message.target_index);
    push_u32(&mut payload, message.target_generation);
    push_i32(&mut payload, message.interaction_x);
    push_i32(&mut payload, message.interaction_y);
    push_i32(&mut payload, message.interaction_width);
    push_i32(&mut payload, message.interaction_height);
    push_u16(&mut payload, message.affected_output_count);
    push_u16(&mut payload, 0);
    payload.extend_from_slice(&message.affected_outputs);
    encode_frame(IpcMessageKind::WmV1ProjectionRequest, transaction, &payload)
}

pub fn decode_wm_v1_projection_request_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProjectionRequest), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProjectionRequest {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let request_id = cursor.u64()?;
    let scene_generation = cursor.u64()?;
    let policy_generation = cursor.u64()?;
    let cause_kind = cursor.u16()?;
    let interaction_phase = cursor.u16()?;
    let interaction_kind = cursor.u16()?;
    let interaction_axis = cursor.u16()?;
    let activation_serial = cursor.u64()?;
    let action = cursor.u64()?;
    let target_index = cursor.u32()?;
    let target_generation = cursor.u32()?;
    let interaction_x = cursor.i32()?;
    let interaction_y = cursor.i32()?;
    let interaction_width = cursor.i32()?;
    let interaction_height = cursor.i32()?;
    let affected_output_count = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    let len = payload.len().saturating_sub(84);
    if len > 128 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "affected_outputs",
            len,
            max: 128,
        });
    }
    let affected_outputs = cursor.slice(len)?.to_vec();
    cursor.finish()?;
    let message = WmV1ProjectionRequest {
        connection_epoch,
        request_id,
        scene_generation,
        policy_generation,
        cause_kind,
        interaction_phase,
        interaction_kind,
        interaction_axis,
        activation_serial,
        action,
        target_index,
        target_generation,
        interaction_x,
        interaction_y,
        interaction_width,
        interaction_height,
        affected_output_count,
        affected_outputs,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionBegin {
    pub connection_epoch: u64,
    pub request_id: u64,
    pub base_generation: u64,
    pub active_output: u64,
    pub chunk_count: u16,
    pub output_count: u16,
    pub placement_count: u32,
    pub indicator_count: u16,
    pub status_count: u16,
}

pub fn encode_wm_v1_projection_begin_frame(
    transaction: TransactionId,
    message: &WmV1ProjectionBegin,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.request_id);
    push_u64(&mut payload, message.base_generation);
    push_u64(&mut payload, message.active_output);
    push_u16(&mut payload, message.chunk_count);
    push_u16(&mut payload, message.output_count);
    push_u32(&mut payload, message.placement_count);
    push_u16(&mut payload, message.indicator_count);
    push_u16(&mut payload, message.status_count);
    encode_frame(IpcMessageKind::WmV1ProjectionBegin, transaction, &payload)
}

pub fn decode_wm_v1_projection_begin_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProjectionBegin), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProjectionBegin {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let request_id = cursor.u64()?;
    let base_generation = cursor.u64()?;
    let active_output = cursor.u64()?;
    let chunk_count = cursor.u16()?;
    let output_count = cursor.u16()?;
    let placement_count = cursor.u32()?;
    let indicator_count = cursor.u16()?;
    let status_count = cursor.u16()?;
    cursor.finish()?;
    let message = WmV1ProjectionBegin {
        connection_epoch,
        request_id,
        base_generation,
        active_output,
        chunk_count,
        output_count,
        placement_count,
        indicator_count,
        status_count,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionChunk {
    pub connection_epoch: u64,
    pub ordinal: u16,
    pub record_kind: u16,
    pub item_count: u32,
    pub data: Vec<u8>,
}

pub fn encode_wm_v1_projection_chunk_frame(
    transaction: TransactionId,
    message: &WmV1ProjectionChunk,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    if message.data.len() > 65520 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "data",
            len: message.data.len(),
            max: 65520,
        });
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u16(&mut payload, message.ordinal);
    push_u16(&mut payload, message.record_kind);
    push_u32(&mut payload, message.item_count);
    payload.extend_from_slice(&message.data);
    encode_frame(IpcMessageKind::WmV1ProjectionChunk, transaction, &payload)
}

pub fn decode_wm_v1_projection_chunk_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProjectionChunk), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProjectionChunk {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let ordinal = cursor.u16()?;
    let record_kind = cursor.u16()?;
    let item_count = cursor.u32()?;
    let len = payload.len().saturating_sub(16);
    if len > 65520 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "data",
            len,
            max: 65520,
        });
    }
    let data = cursor.slice(len)?.to_vec();
    cursor.finish()?;
    let message = WmV1ProjectionChunk {
        connection_epoch,
        ordinal,
        record_kind,
        item_count,
        data,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionEnd {
    pub connection_epoch: u64,
    pub request_id: u64,
    pub base_generation: u64,
    pub chunk_count: u16,
}

pub fn encode_wm_v1_projection_end_frame(
    transaction: TransactionId,
    message: &WmV1ProjectionEnd,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.request_id);
    push_u64(&mut payload, message.base_generation);
    push_u16(&mut payload, message.chunk_count);
    push_u16(&mut payload, 0);
    encode_frame(IpcMessageKind::WmV1ProjectionEnd, transaction, &payload)
}

pub fn decode_wm_v1_projection_end_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProjectionEnd), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProjectionEnd {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let request_id = cursor.u64()?;
    let base_generation = cursor.u64()?;
    let chunk_count = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    cursor.finish()?;
    let message = WmV1ProjectionEnd {
        connection_epoch,
        request_id,
        base_generation,
        chunk_count,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionOutcome {
    pub connection_epoch: u64,
    pub request_id: u64,
    pub scene_generation: u64,
    pub outcome: u16,
}

pub fn encode_wm_v1_projection_outcome_frame(
    transaction: TransactionId,
    message: &WmV1ProjectionOutcome,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.request_id);
    push_u64(&mut payload, message.scene_generation);
    push_u16(&mut payload, message.outcome);
    push_u16(&mut payload, 0);
    encode_frame(IpcMessageKind::WmV1ProjectionOutcome, transaction, &payload)
}

pub fn decode_wm_v1_projection_outcome_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProjectionOutcome), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProjectionOutcome {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let request_id = cursor.u64()?;
    let scene_generation = cursor.u64()?;
    let outcome = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    cursor.finish()?;
    let message = WmV1ProjectionOutcome {
        connection_epoch,
        request_id,
        scene_generation,
        outcome,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1PolicyConfiguration {
    pub connection_epoch: u64,
    pub configuration_generation: u64,
    pub action_count: u16,
    pub style_bits: u16,
    pub focus_ring_width: u32,
    pub focus_ring_color: u32,
    pub frame_width: u32,
    pub frame_focused_color: u32,
    pub frame_unfocused_color: u32,
    pub actions: Vec<u8>,
}

pub fn encode_wm_v1_policy_configuration_frame(
    transaction: TransactionId,
    message: &WmV1PolicyConfiguration,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    if message.actions.len() > 35840 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "actions",
            len: message.actions.len(),
            max: 35840,
        });
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.configuration_generation);
    push_u16(&mut payload, message.action_count);
    push_u16(&mut payload, message.style_bits);
    push_u32(&mut payload, message.focus_ring_width);
    push_u32(&mut payload, message.focus_ring_color);
    push_u32(&mut payload, message.frame_width);
    push_u32(&mut payload, message.frame_focused_color);
    push_u32(&mut payload, message.frame_unfocused_color);
    payload.extend_from_slice(&message.actions);
    encode_frame(
        IpcMessageKind::WmV1PolicyConfiguration,
        transaction,
        &payload,
    )
}

pub fn decode_wm_v1_policy_configuration_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1PolicyConfiguration), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1PolicyConfiguration {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let configuration_generation = cursor.u64()?;
    let action_count = cursor.u16()?;
    let style_bits = cursor.u16()?;
    let focus_ring_width = cursor.u32()?;
    let focus_ring_color = cursor.u32()?;
    let frame_width = cursor.u32()?;
    let frame_focused_color = cursor.u32()?;
    let frame_unfocused_color = cursor.u32()?;
    let len = payload.len().saturating_sub(40);
    if len > 35840 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "actions",
            len,
            max: 35840,
        });
    }
    let actions = cursor.slice(len)?.to_vec();
    cursor.finish()?;
    let message = WmV1PolicyConfiguration {
        connection_epoch,
        configuration_generation,
        action_count,
        style_bits,
        focus_ring_width,
        focus_ring_color,
        frame_width,
        frame_focused_color,
        frame_unfocused_color,
        actions,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1PolicyConfigurationOutcome {
    pub connection_epoch: u64,
    pub configuration_generation: u64,
    pub outcome: u16,
}

pub fn encode_wm_v1_policy_configuration_outcome_frame(
    transaction: TransactionId,
    message: &WmV1PolicyConfigurationOutcome,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.configuration_generation);
    push_u16(&mut payload, message.outcome);
    push_u16(&mut payload, 0);
    encode_frame(
        IpcMessageKind::WmV1PolicyConfigurationOutcome,
        transaction,
        &payload,
    )
}

pub fn decode_wm_v1_policy_configuration_outcome_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1PolicyConfigurationOutcome), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1PolicyConfigurationOutcome {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let configuration_generation = cursor.u64()?;
    let outcome = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    cursor.finish()?;
    let message = WmV1PolicyConfigurationOutcome {
        connection_epoch,
        configuration_generation,
        outcome,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1PolicyDirty {
    pub connection_epoch: u64,
    pub policy_generation: u64,
    pub affected_output_count: u16,
    pub affected_outputs: Vec<u8>,
}

pub fn encode_wm_v1_policy_dirty_frame(
    transaction: TransactionId,
    message: &WmV1PolicyDirty,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    if message.affected_outputs.len() > 128 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "affected_outputs",
            len: message.affected_outputs.len(),
            max: 128,
        });
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.policy_generation);
    push_u16(&mut payload, message.affected_output_count);
    push_u16(&mut payload, 0);
    payload.extend_from_slice(&message.affected_outputs);
    encode_frame(IpcMessageKind::WmV1PolicyDirty, transaction, &payload)
}

pub fn decode_wm_v1_policy_dirty_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1PolicyDirty), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1PolicyDirty {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let policy_generation = cursor.u64()?;
    let affected_output_count = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    let len = payload.len().saturating_sub(20);
    if len > 128 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "affected_outputs",
            len,
            max: 128,
        });
    }
    let affected_outputs = cursor.slice(len)?.to_vec();
    cursor.finish()?;
    let message = WmV1PolicyDirty {
        connection_epoch,
        policy_generation,
        affected_output_count,
        affected_outputs,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SessionOperationRequest {
    pub connection_epoch: u64,
    pub request_id: u64,
    pub operation: u64,
    pub target_index: u32,
    pub target_generation: u32,
}

pub fn encode_wm_v1_session_operation_request_frame(
    transaction: TransactionId,
    message: &WmV1SessionOperationRequest,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.request_id);
    push_u64(&mut payload, message.operation);
    push_u32(&mut payload, message.target_index);
    push_u32(&mut payload, message.target_generation);
    encode_frame(
        IpcMessageKind::WmV1SessionOperationRequest,
        transaction,
        &payload,
    )
}

pub fn decode_wm_v1_session_operation_request_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1SessionOperationRequest), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1SessionOperationRequest {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let request_id = cursor.u64()?;
    let operation = cursor.u64()?;
    let target_index = cursor.u32()?;
    let target_generation = cursor.u32()?;
    cursor.finish()?;
    let message = WmV1SessionOperationRequest {
        connection_epoch,
        request_id,
        operation,
        target_index,
        target_generation,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SessionOperationOutcome {
    pub connection_epoch: u64,
    pub request_id: u64,
    pub outcome: u16,
}

pub fn encode_wm_v1_session_operation_outcome_frame(
    transaction: TransactionId,
    message: &WmV1SessionOperationOutcome,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.request_id);
    push_u16(&mut payload, message.outcome);
    push_u16(&mut payload, 0);
    encode_frame(
        IpcMessageKind::WmV1SessionOperationOutcome,
        transaction,
        &payload,
    )
}

pub fn decode_wm_v1_session_operation_outcome_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1SessionOperationOutcome), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1SessionOperationOutcome {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let request_id = cursor.u64()?;
    let outcome = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    cursor.finish()?;
    let message = WmV1SessionOperationOutcome {
        connection_epoch,
        request_id,
        outcome,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProfilePrepare {
    pub connection_epoch: u64,
    pub profile_generation: u64,
    pub profile_digest: [u8; 32],
}

pub fn encode_wm_v1_profile_prepare_frame(
    transaction: TransactionId,
    message: &WmV1ProfilePrepare,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.profile_generation);
    payload.extend_from_slice(&message.profile_digest);
    encode_frame(IpcMessageKind::WmV1ProfilePrepare, transaction, &payload)
}

pub fn decode_wm_v1_profile_prepare_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProfilePrepare), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProfilePrepare {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let profile_generation = cursor.u64()?;
    let mut profile_digest = [0u8; 32];
    profile_digest.copy_from_slice(cursor.slice(32)?);
    cursor.finish()?;
    let message = WmV1ProfilePrepare {
        connection_epoch,
        profile_generation,
        profile_digest,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProfilePrepared {
    pub connection_epoch: u64,
    pub profile_generation: u64,
    pub profile_digest: [u8; 32],
    pub outcome: u16,
}

pub fn encode_wm_v1_profile_prepared_frame(
    transaction: TransactionId,
    message: &WmV1ProfilePrepared,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.profile_generation);
    payload.extend_from_slice(&message.profile_digest);
    push_u16(&mut payload, message.outcome);
    push_u16(&mut payload, 0);
    encode_frame(IpcMessageKind::WmV1ProfilePrepared, transaction, &payload)
}

pub fn decode_wm_v1_profile_prepared_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProfilePrepared), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProfilePrepared {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let profile_generation = cursor.u64()?;
    let mut profile_digest = [0u8; 32];
    profile_digest.copy_from_slice(cursor.slice(32)?);
    let outcome = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    cursor.finish()?;
    let message = WmV1ProfilePrepared {
        connection_epoch,
        profile_generation,
        profile_digest,
        outcome,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProfileActivate {
    pub connection_epoch: u64,
    pub profile_generation: u64,
    pub profile_digest: [u8; 32],
}

pub fn encode_wm_v1_profile_activate_frame(
    transaction: TransactionId,
    message: &WmV1ProfileActivate,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.profile_generation);
    payload.extend_from_slice(&message.profile_digest);
    encode_frame(IpcMessageKind::WmV1ProfileActivate, transaction, &payload)
}

pub fn decode_wm_v1_profile_activate_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProfileActivate), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProfileActivate {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let profile_generation = cursor.u64()?;
    let mut profile_digest = [0u8; 32];
    profile_digest.copy_from_slice(cursor.slice(32)?);
    cursor.finish()?;
    let message = WmV1ProfileActivate {
        connection_epoch,
        profile_generation,
        profile_digest,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProfileActive {
    pub connection_epoch: u64,
    pub profile_generation: u64,
    pub profile_digest: [u8; 32],
    pub outcome: u16,
}

pub fn encode_wm_v1_profile_active_frame(
    transaction: TransactionId,
    message: &WmV1ProfileActive,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.profile_generation);
    payload.extend_from_slice(&message.profile_digest);
    push_u16(&mut payload, message.outcome);
    push_u16(&mut payload, 0);
    encode_frame(IpcMessageKind::WmV1ProfileActive, transaction, &payload)
}

pub fn decode_wm_v1_profile_active_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProfileActive), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProfileActive {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let profile_generation = cursor.u64()?;
    let mut profile_digest = [0u8; 32];
    profile_digest.copy_from_slice(cursor.slice(32)?);
    let outcome = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    cursor.finish()?;
    let message = WmV1ProfileActive {
        connection_epoch,
        profile_generation,
        profile_digest,
        outcome,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProfileRollback {
    pub connection_epoch: u64,
    pub profile_generation: u64,
    pub profile_digest: [u8; 32],
}

pub fn encode_wm_v1_profile_rollback_frame(
    transaction: TransactionId,
    message: &WmV1ProfileRollback,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.profile_generation);
    payload.extend_from_slice(&message.profile_digest);
    encode_frame(IpcMessageKind::WmV1ProfileRollback, transaction, &payload)
}

pub fn decode_wm_v1_profile_rollback_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProfileRollback), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProfileRollback {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let profile_generation = cursor.u64()?;
    let mut profile_digest = [0u8; 32];
    profile_digest.copy_from_slice(cursor.slice(32)?);
    cursor.finish()?;
    let message = WmV1ProfileRollback {
        connection_epoch,
        profile_generation,
        profile_digest,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProfileRolledBack {
    pub connection_epoch: u64,
    pub profile_generation: u64,
    pub profile_digest: [u8; 32],
    pub outcome: u16,
}

pub fn encode_wm_v1_profile_rolled_back_frame(
    transaction: TransactionId,
    message: &WmV1ProfileRolledBack,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.profile_generation);
    payload.extend_from_slice(&message.profile_digest);
    push_u16(&mut payload, message.outcome);
    push_u16(&mut payload, 0);
    encode_frame(IpcMessageKind::WmV1ProfileRolledBack, transaction, &payload)
}

pub fn decode_wm_v1_profile_rolled_back_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1ProfileRolledBack), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1ProfileRolledBack {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let profile_generation = cursor.u64()?;
    let mut profile_digest = [0u8; 32];
    profile_digest.copy_from_slice(cursor.slice(32)?);
    let outcome = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    cursor.finish()?;
    let message = WmV1ProfileRolledBack {
        connection_epoch,
        profile_generation,
        profile_digest,
        outcome,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1OutputActionRequest {
    pub connection_epoch: u64,
    pub request_id: u64,
    pub scene_generation: u64,
    pub policy_generation: u64,
    pub activation_serial: u64,
    pub action: u64,
    pub output: u64,
    pub output_generation: u64,
    pub affected_output_count: u16,
    pub affected_outputs: Vec<u8>,
}

pub fn encode_wm_v1_output_action_request_frame(
    transaction: TransactionId,
    message: &WmV1OutputActionRequest,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    if message.affected_outputs.len() > 128 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "affected_outputs",
            len: message.affected_outputs.len(),
            max: 128,
        });
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.request_id);
    push_u64(&mut payload, message.scene_generation);
    push_u64(&mut payload, message.policy_generation);
    push_u64(&mut payload, message.activation_serial);
    push_u64(&mut payload, message.action);
    push_u64(&mut payload, message.output);
    push_u64(&mut payload, message.output_generation);
    push_u16(&mut payload, message.affected_output_count);
    push_u16(&mut payload, 0);
    payload.extend_from_slice(&message.affected_outputs);
    encode_frame(
        IpcMessageKind::WmV1OutputActionRequest,
        transaction,
        &payload,
    )
}

pub fn decode_wm_v1_output_action_request_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1OutputActionRequest), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1OutputActionRequest {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let request_id = cursor.u64()?;
    let scene_generation = cursor.u64()?;
    let policy_generation = cursor.u64()?;
    let activation_serial = cursor.u64()?;
    let action = cursor.u64()?;
    let output = cursor.u64()?;
    let output_generation = cursor.u64()?;
    let affected_output_count = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    let len = payload.len().saturating_sub(68);
    if len > 128 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "affected_outputs",
            len,
            max: 128,
        });
    }
    let affected_outputs = cursor.slice(len)?.to_vec();
    cursor.finish()?;
    let message = WmV1OutputActionRequest {
        connection_epoch,
        request_id,
        scene_generation,
        policy_generation,
        activation_serial,
        action,
        output,
        output_generation,
        affected_output_count,
        affected_outputs,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1PresentationActionRequest {
    pub connection_epoch: u64,
    pub request_id: u64,
    pub scene_generation: u64,
    pub policy_generation: u64,
    pub activation_serial: u64,
    pub action: u64,
    pub output: u64,
    pub output_generation: u64,
    pub publication_generation: u64,
    pub presentation_epoch: u64,
    pub target_id: u64,
    pub target_generation: u64,
    pub affected_output_count: u16,
    pub affected_outputs: Vec<u8>,
}

pub fn encode_wm_v1_presentation_action_request_frame(
    transaction: TransactionId,
    message: &WmV1PresentationActionRequest,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    if message.affected_outputs.len() > 128 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "affected_outputs",
            len: message.affected_outputs.len(),
            max: 128,
        });
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.request_id);
    push_u64(&mut payload, message.scene_generation);
    push_u64(&mut payload, message.policy_generation);
    push_u64(&mut payload, message.activation_serial);
    push_u64(&mut payload, message.action);
    push_u64(&mut payload, message.output);
    push_u64(&mut payload, message.output_generation);
    push_u64(&mut payload, message.publication_generation);
    push_u64(&mut payload, message.presentation_epoch);
    push_u64(&mut payload, message.target_id);
    push_u64(&mut payload, message.target_generation);
    push_u16(&mut payload, message.affected_output_count);
    push_u16(&mut payload, 0);
    payload.extend_from_slice(&message.affected_outputs);
    encode_frame(
        IpcMessageKind::WmV1PresentationActionRequest,
        transaction,
        &payload,
    )
}

pub fn decode_wm_v1_presentation_action_request_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1PresentationActionRequest), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1PresentationActionRequest {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let request_id = cursor.u64()?;
    let scene_generation = cursor.u64()?;
    let policy_generation = cursor.u64()?;
    let activation_serial = cursor.u64()?;
    let action = cursor.u64()?;
    let output = cursor.u64()?;
    let output_generation = cursor.u64()?;
    let publication_generation = cursor.u64()?;
    let presentation_epoch = cursor.u64()?;
    let target_id = cursor.u64()?;
    let target_generation = cursor.u64()?;
    let affected_output_count = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    let len = payload.len().saturating_sub(100);
    if len > 128 {
        return Err(IpcCodecError::FieldTooLarge {
            field: "affected_outputs",
            len,
            max: 128,
        });
    }
    let affected_outputs = cursor.slice(len)?.to_vec();
    cursor.finish()?;
    let message = WmV1PresentationActionRequest {
        connection_epoch,
        request_id,
        scene_generation,
        policy_generation,
        activation_serial,
        action,
        output,
        output_generation,
        publication_generation,
        presentation_epoch,
        target_id,
        target_generation,
        affected_output_count,
        affected_outputs,
    };
    Ok((header.transaction, message))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1PresentationOutcome {
    pub connection_epoch: u64,
    pub publication_generation: u64,
    pub output: u64,
    pub output_generation: u64,
    pub presentation_epoch: u64,
    pub outcome: u16,
}

pub fn encode_wm_v1_presentation_outcome_frame(
    transaction: TransactionId,
    message: &WmV1PresentationOutcome,
) -> Result<Vec<u8>, IpcCodecError> {
    if !transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut payload = Vec::new();
    push_u64(&mut payload, message.connection_epoch);
    push_u64(&mut payload, message.publication_generation);
    push_u64(&mut payload, message.output);
    push_u64(&mut payload, message.output_generation);
    push_u64(&mut payload, message.presentation_epoch);
    push_u16(&mut payload, message.outcome);
    push_u16(&mut payload, 0);
    encode_frame(
        IpcMessageKind::WmV1PresentationOutcome,
        transaction,
        &payload,
    )
}

pub fn decode_wm_v1_presentation_outcome_frame(
    frame: &[u8],
) -> Result<(TransactionId, WmV1PresentationOutcome), IpcCodecError> {
    let (header, payload) = decode_frame(frame)?;
    if header.message_kind != IpcMessageKind::WmV1PresentationOutcome {
        return Err(IpcCodecError::InvalidEnum {
            field: "message_kind",
            value: header.message_kind as u32,
        });
    }
    if !header.transaction.is_valid() {
        return Err(IpcCodecError::InvalidTransaction(0));
    }
    let mut cursor = Cursor::new(payload);
    let connection_epoch = cursor.u64()?;
    let publication_generation = cursor.u64()?;
    let output = cursor.u64()?;
    let output_generation = cursor.u64()?;
    let presentation_epoch = cursor.u64()?;
    let outcome = cursor.u16()?;
    let reserved = cursor.u16()?;
    if reserved != 0 {
        return Err(IpcCodecError::ReservedNonZero(reserved as u32));
    }
    cursor.finish()?;
    let message = WmV1PresentationOutcome {
        connection_epoch,
        publication_generation,
        output,
        output_generation,
        presentation_epoch,
        outcome,
    };
    Ok((header.transaction, message))
}
