[package]
name = "sophia-runtime"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
sophia-wake = { path = "../sophia-wake" }
rustix = { version = "1.1", default-features = false, features = ["net", "process", "std", "event", "rand"] }
sophia-linux-peer = { path = "../sophia-linux-peer" }
sophia-9p = { path = "../sophia-9p" }
sophia-protocol = { path = "../sophia-protocol" }
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
rustix = { workspace = true, features = ["fs"] }
serde_json = "1"
sha2.workspace = true
sophia-engine = { path = "../sophia-engine" }
sophia-shell-client = { workspace = true }

[lints]
workspace = true
