// @generated by sophia-policy-protocol-gen; do not edit.
// Source: protocol/sophia-wm-files-v1.kdl (row-layouts)

use crate::BinaryCodecError;
use crate::byte_cursor::{Cursor, push_i32, push_u16, push_u32, push_u64};

pub const SOPHIA_WM_INTERFACE_MAJOR: u16 = 1;
pub const SOPHIA_WM_INTERFACE_REVISION: u16 = 3;
pub const SOPHIA_WM_MAX_OUTPUTS: usize = 16;
pub const SOPHIA_WM_MAX_SURFACES: usize = 1024;
pub const SOPHIA_WM_MAX_BINDINGS: usize = 256;

pub const SOPHIA_WM_CAPABILITY_BINDINGS: u64 = 1 << 0;
pub const SOPHIA_WM_CAPABILITY_ACTIONS: u64 = 1 << 1;
pub const SOPHIA_WM_CAPABILITY_MULTI_OUTPUT: u64 = 1 << 2;
pub const SOPHIA_WM_CAPABILITY_POINTER_INTERACTIONS: u64 = 1 << 3;
pub const SOPHIA_WM_CAPABILITY_CHROME: u64 = 1 << 4;
pub const SOPHIA_WM_CAPABILITY_POLICY_DIRTY: u64 = 1 << 5;
pub const SOPHIA_WM_CAPABILITY_CONFIGURATION: u64 = 1 << 6;
pub const SOPHIA_WM_CAPABILITY_SESSION_OPERATIONS: u64 = 1 << 7;
pub const SOPHIA_WM_CAPABILITY_INDICATORS: u64 = 1 << 8;
pub const SOPHIA_WM_CAPABILITY_PROFILE_ACTIVATION: u64 = 1 << 9;
pub const SOPHIA_WM_CAPABILITY_LAUNCH_PLACEMENT: u64 = 1 << 10;
pub const SOPHIA_WM_CAPABILITY_TAB_GROUPS: u64 = 1 << 11;
pub const SOPHIA_WM_CAPABILITY_TRANSLATION_GROUPS: u64 = 1 << 12;
pub const SOPHIA_WM_CAPABILITY_POINTER_FOCUS: u64 = 1 << 13;
pub const SOPHIA_WM_CAPABILITY_LAUNCH_ORIGIN: u64 = 1 << 14;
pub const SOPHIA_WM_CAPABILITY_OUTPUT_ACTIONS: u64 = 1 << 15;
pub const SOPHIA_WM_CAPABILITY_OUTPUT_POLICY_KEYS: u64 = 1 << 16;
pub const SOPHIA_WM_CAPABILITY_OUTPUT_LAUNCH_CONTEXT: u64 = 1 << 17;
pub const SOPHIA_WM_CAPABILITY_SURFACE_INSTANCES: u64 = 1 << 18;
pub const SOPHIA_WM_CAPABILITY_PRESENTATION_ACTIONS: u64 = 1 << 19;
pub const SOPHIA_WM_CAPABILITY_ACTION_LIFECYCLE: u64 = 1 << 20;
pub const SOPHIA_WM_CAPABILITY_CHORD_ACTIONS: u64 = 1 << 21;
pub const SOPHIA_WM_CAPABILITY_HELD_CAPTURE: u64 = 1 << 22;

pub const SOPHIA_WM_OUTCOME_COMMITTED: u16 = 1;
pub const SOPHIA_WM_OUTCOME_REJECTED_STALE: u16 = 2;
pub const SOPHIA_WM_OUTCOME_REJECTED_INVALID: u16 = 3;
pub const SOPHIA_WM_OUTCOME_TIMED_OUT: u16 = 4;
pub const SOPHIA_WM_OUTCOME_DISCONNECTED: u16 = 5;
pub const SOPHIA_WM_OUTCOME_PROFILE_ACCEPTED: u16 = 1;
pub const SOPHIA_WM_OUTCOME_PROFILE_REJECTED_IDENTITY: u16 = 2;
pub const SOPHIA_WM_OUTCOME_PROFILE_REJECTED_STATE: u16 = 3;

pub const SNAPSHOT_OUTPUT_RECORD_KIND: u16 = 1;
pub const SNAPSHOT_OUTPUT_RECORD_SIZE: usize = 56;
pub const SNAPSHOT_OUTPUT_RECORD_MAX: usize = 16;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SnapshotOutputRecord {
    pub output: u64,
    pub generation: u64,
    pub focus_index: u32,
    pub focus_generation: u32,
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
    pub work_x: i32,
    pub work_y: i32,
    pub work_width: i32,
    pub work_height: i32,
}

pub fn encode_wm_v1_snapshot_output_records(
    records: &[WmV1SnapshotOutputRecord],
) -> Result<Vec<u8>, BinaryCodecError> {
    if records.len() > 16 {
        return Err(BinaryCodecError::CountTooLarge {
            count: records.len(),
            max: 16,
        });
    }
    let mut data = Vec::with_capacity(records.len() * 56);
    for record in records {
        push_u64(&mut data, record.output);
        push_u64(&mut data, record.generation);
        push_u32(&mut data, record.focus_index);
        push_u32(&mut data, record.focus_generation);
        push_i32(&mut data, record.x);
        push_i32(&mut data, record.y);
        push_i32(&mut data, record.width);
        push_i32(&mut data, record.height);
        push_i32(&mut data, record.work_x);
        push_i32(&mut data, record.work_y);
        push_i32(&mut data, record.work_width);
        push_i32(&mut data, record.work_height);
    }
    Ok(data)
}

pub fn decode_wm_v1_snapshot_output_records(
    data: &[u8],
    item_count: u32,
) -> Result<Vec<WmV1SnapshotOutputRecord>, BinaryCodecError> {
    let count = item_count as usize;
    if count > 16 {
        return Err(BinaryCodecError::CountTooLarge { count, max: 16 });
    }
    let expected = count
        .checked_mul(56)
        .ok_or(BinaryCodecError::CountTooLarge { count, max: 16 })?;
    if data.len() < expected {
        return Err(BinaryCodecError::Truncated);
    }
    if data.len() > expected {
        return Err(BinaryCodecError::TrailingBytes(data.len() - expected));
    }
    let mut cursor = Cursor::new(data);
    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let output = cursor.u64()?;
        let generation = cursor.u64()?;
        let focus_index = cursor.u32()?;
        let focus_generation = cursor.u32()?;
        let x = cursor.i32()?;
        let y = cursor.i32()?;
        let width = cursor.i32()?;
        let height = cursor.i32()?;
        let work_x = cursor.i32()?;
        let work_y = cursor.i32()?;
        let work_width = cursor.i32()?;
        let work_height = cursor.i32()?;
        records.push(WmV1SnapshotOutputRecord {
            output,
            generation,
            focus_index,
            focus_generation,
            x,
            y,
            width,
            height,
            work_x,
            work_y,
            work_width,
            work_height,
        });
    }
    cursor.finish()?;
    Ok(records)
}

pub const SNAPSHOT_SURFACE_RECORD_KIND: u16 = 2;
pub const SNAPSHOT_SURFACE_RECORD_SIZE: usize = 80;
pub const SNAPSHOT_SURFACE_RECORD_MAX: usize = 1024;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SnapshotSurfaceRecord {
    pub surface_index: u32,
    pub surface_generation: u32,
    pub state_generation: u64,
    pub current_output: u64,
    pub capability_bits: u16,
    pub kind: u16,
    pub request_state_bits: u16,
    pub current_state_bits: u16,
    pub transient_index: u32,
    pub transient_generation: u32,
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
    pub min_width: i32,
    pub min_height: i32,
    pub max_width: i32,
    pub max_height: i32,
    pub exact_width: i32,
    pub exact_height: i32,
}

pub fn encode_wm_v1_snapshot_surface_records(
    records: &[WmV1SnapshotSurfaceRecord],
) -> Result<Vec<u8>, BinaryCodecError> {
    if records.len() > 1024 {
        return Err(BinaryCodecError::CountTooLarge {
            count: records.len(),
            max: 1024,
        });
    }
    let mut data = Vec::with_capacity(records.len() * 80);
    for record in records {
        push_u32(&mut data, record.surface_index);
        push_u32(&mut data, record.surface_generation);
        push_u64(&mut data, record.state_generation);
        push_u64(&mut data, record.current_output);
        push_u16(&mut data, record.capability_bits);
        push_u16(&mut data, record.kind);
        push_u16(&mut data, record.request_state_bits);
        push_u16(&mut data, record.current_state_bits);
        push_u32(&mut data, record.transient_index);
        push_u32(&mut data, record.transient_generation);
        push_i32(&mut data, record.x);
        push_i32(&mut data, record.y);
        push_i32(&mut data, record.width);
        push_i32(&mut data, record.height);
        push_i32(&mut data, record.min_width);
        push_i32(&mut data, record.min_height);
        push_i32(&mut data, record.max_width);
        push_i32(&mut data, record.max_height);
        push_i32(&mut data, record.exact_width);
        push_i32(&mut data, record.exact_height);
    }
    Ok(data)
}

pub fn decode_wm_v1_snapshot_surface_records(
    data: &[u8],
    item_count: u32,
) -> Result<Vec<WmV1SnapshotSurfaceRecord>, BinaryCodecError> {
    let count = item_count as usize;
    if count > 1024 {
        return Err(BinaryCodecError::CountTooLarge { count, max: 1024 });
    }
    let expected = count
        .checked_mul(80)
        .ok_or(BinaryCodecError::CountTooLarge { count, max: 1024 })?;
    if data.len() < expected {
        return Err(BinaryCodecError::Truncated);
    }
    if data.len() > expected {
        return Err(BinaryCodecError::TrailingBytes(data.len() - expected));
    }
    let mut cursor = Cursor::new(data);
    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let surface_index = cursor.u32()?;
        let surface_generation = cursor.u32()?;
        let state_generation = cursor.u64()?;
        let current_output = cursor.u64()?;
        let capability_bits = cursor.u16()?;
        let kind = cursor.u16()?;
        let request_state_bits = cursor.u16()?;
        let current_state_bits = cursor.u16()?;
        let transient_index = cursor.u32()?;
        let transient_generation = cursor.u32()?;
        let x = cursor.i32()?;
        let y = cursor.i32()?;
        let width = cursor.i32()?;
        let height = cursor.i32()?;
        let min_width = cursor.i32()?;
        let min_height = cursor.i32()?;
        let max_width = cursor.i32()?;
        let max_height = cursor.i32()?;
        let exact_width = cursor.i32()?;
        let exact_height = cursor.i32()?;
        records.push(WmV1SnapshotSurfaceRecord {
            surface_index,
            surface_generation,
            state_generation,
            current_output,
            capability_bits,
            kind,
            request_state_bits,
            current_state_bits,
            transient_index,
            transient_generation,
            x,
            y,
            width,
            height,
            min_width,
            min_height,
            max_width,
            max_height,
            exact_width,
            exact_height,
        });
    }
    cursor.finish()?;
    Ok(records)
}

pub const SNAPSHOT_ACTION_RECORD_KIND: u16 = 3;
pub const SNAPSHOT_ACTION_RECORD_SIZE: usize = 140;
pub const SNAPSHOT_ACTION_RECORD_MAX: usize = 256;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SnapshotActionRecord {
    pub action: u64,
    pub session_operation_slot: u16,
    pub name_len: u16,
    pub name: [u8; 128],
}

pub fn encode_wm_v1_snapshot_action_records(
    records: &[WmV1SnapshotActionRecord],
) -> Result<Vec<u8>, BinaryCodecError> {
    if records.len() > 256 {
        return Err(BinaryCodecError::CountTooLarge {
            count: records.len(),
            max: 256,
        });
    }
    let mut data = Vec::with_capacity(records.len() * 140);
    for record in records {
        push_u64(&mut data, record.action);
        push_u16(&mut data, record.session_operation_slot);
        push_u16(&mut data, record.name_len);
        data.extend_from_slice(&record.name);
    }
    Ok(data)
}

pub fn decode_wm_v1_snapshot_action_records(
    data: &[u8],
    item_count: u32,
) -> Result<Vec<WmV1SnapshotActionRecord>, BinaryCodecError> {
    let count = item_count as usize;
    if count > 256 {
        return Err(BinaryCodecError::CountTooLarge { count, max: 256 });
    }
    let expected = count
        .checked_mul(140)
        .ok_or(BinaryCodecError::CountTooLarge { count, max: 256 })?;
    if data.len() < expected {
        return Err(BinaryCodecError::Truncated);
    }
    if data.len() > expected {
        return Err(BinaryCodecError::TrailingBytes(data.len() - expected));
    }
    let mut cursor = Cursor::new(data);
    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let action = cursor.u64()?;
        let session_operation_slot = cursor.u16()?;
        let name_len = cursor.u16()?;
        let mut name = [0u8; 128];
        name.copy_from_slice(cursor.slice(128)?);
        records.push(WmV1SnapshotActionRecord {
            action,
            session_operation_slot,
            name_len,
            name,
        });
    }
    cursor.finish()?;
    Ok(records)
}

pub const SNAPSHOT_SESSION_OPERATION_RECORD_KIND: u16 = 4;
pub const SNAPSHOT_SESSION_OPERATION_RECORD_SIZE: usize = 12;
pub const SNAPSHOT_SESSION_OPERATION_RECORD_MAX: usize = 256;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1SnapshotSessionOperationRecord {
    pub operation: u64,
    pub slot: u16,
    pub target_bits: u16,
}

pub fn encode_wm_v1_snapshot_session_operation_records(
    records: &[WmV1SnapshotSessionOperationRecord],
) -> Result<Vec<u8>, BinaryCodecError> {
    if records.len() > 256 {
        return Err(BinaryCodecError::CountTooLarge {
            count: records.len(),
            max: 256,
        });
    }
    let mut data = Vec::with_capacity(records.len() * 12);
    for record in records {
        push_u64(&mut data, record.operation);
        push_u16(&mut data, record.slot);
        push_u16(&mut data, record.target_bits);
    }
    Ok(data)
}

pub fn decode_wm_v1_snapshot_session_operation_records(
    data: &[u8],
    item_count: u32,
) -> Result<Vec<WmV1SnapshotSessionOperationRecord>, BinaryCodecError> {
    let count = item_count as usize;
    if count > 256 {
        return Err(BinaryCodecError::CountTooLarge { count, max: 256 });
    }
    let expected = count
        .checked_mul(12)
        .ok_or(BinaryCodecError::CountTooLarge { count, max: 256 })?;
    if data.len() < expected {
        return Err(BinaryCodecError::Truncated);
    }
    if data.len() > expected {
        return Err(BinaryCodecError::TrailingBytes(data.len() - expected));
    }
    let mut cursor = Cursor::new(data);
    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let operation = cursor.u64()?;
        let slot = cursor.u16()?;
        let target_bits = cursor.u16()?;
        records.push(WmV1SnapshotSessionOperationRecord {
            operation,
            slot,
            target_bits,
        });
    }
    cursor.finish()?;
    Ok(records)
}

pub const PROJECTION_OUTPUT_RECORD_KIND: u16 = 1;
pub const PROJECTION_OUTPUT_RECORD_SIZE: usize = 24;
pub const PROJECTION_OUTPUT_RECORD_MAX: usize = 16;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionOutputRecord {
    pub output: u64,
    pub placement_count: u32,
    pub focus_index: u32,
    pub focus_generation: u32,
}

pub fn encode_wm_v1_projection_output_records(
    records: &[WmV1ProjectionOutputRecord],
) -> Result<Vec<u8>, BinaryCodecError> {
    if records.len() > 16 {
        return Err(BinaryCodecError::CountTooLarge {
            count: records.len(),
            max: 16,
        });
    }
    let mut data = Vec::with_capacity(records.len() * 24);
    for record in records {
        push_u64(&mut data, record.output);
        push_u32(&mut data, record.placement_count);
        push_u32(&mut data, record.focus_index);
        push_u32(&mut data, record.focus_generation);
        push_u32(&mut data, 0);
    }
    Ok(data)
}

pub fn decode_wm_v1_projection_output_records(
    data: &[u8],
    item_count: u32,
) -> Result<Vec<WmV1ProjectionOutputRecord>, BinaryCodecError> {
    let count = item_count as usize;
    if count > 16 {
        return Err(BinaryCodecError::CountTooLarge { count, max: 16 });
    }
    let expected = count
        .checked_mul(24)
        .ok_or(BinaryCodecError::CountTooLarge { count, max: 16 })?;
    if data.len() < expected {
        return Err(BinaryCodecError::Truncated);
    }
    if data.len() > expected {
        return Err(BinaryCodecError::TrailingBytes(data.len() - expected));
    }
    let mut cursor = Cursor::new(data);
    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let output = cursor.u64()?;
        let placement_count = cursor.u32()?;
        let focus_index = cursor.u32()?;
        let focus_generation = cursor.u32()?;
        let reserved = cursor.u32()?;
        if reserved != 0 {
            return Err(BinaryCodecError::ReservedNonZero(reserved));
        }
        records.push(WmV1ProjectionOutputRecord {
            output,
            placement_count,
            focus_index,
            focus_generation,
        });
    }
    cursor.finish()?;
    Ok(records)
}

pub const PROJECTION_PLACEMENT_RECORD_KIND: u16 = 2;
pub const PROJECTION_PLACEMENT_RECORD_SIZE: usize = 60;
pub const PROJECTION_PLACEMENT_RECORD_MAX: usize = 1024;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionPlacementRecord {
    pub surface_index: u32,
    pub surface_generation: u32,
    pub state_generation: u64,
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
    pub requested_width: i32,
    pub requested_height: i32,
    pub crop_x: i32,
    pub crop_y: i32,
    pub crop_width: i32,
    pub crop_height: i32,
    pub transform: u16,
    pub presentation_bits: u16,
}

pub fn encode_wm_v1_projection_placement_records(
    records: &[WmV1ProjectionPlacementRecord],
) -> Result<Vec<u8>, BinaryCodecError> {
    if records.len() > 1024 {
        return Err(BinaryCodecError::CountTooLarge {
            count: records.len(),
            max: 1024,
        });
    }
    let mut data = Vec::with_capacity(records.len() * 60);
    for record in records {
        push_u32(&mut data, record.surface_index);
        push_u32(&mut data, record.surface_generation);
        push_u64(&mut data, record.state_generation);
        push_i32(&mut data, record.x);
        push_i32(&mut data, record.y);
        push_i32(&mut data, record.width);
        push_i32(&mut data, record.height);
        push_i32(&mut data, record.requested_width);
        push_i32(&mut data, record.requested_height);
        push_i32(&mut data, record.crop_x);
        push_i32(&mut data, record.crop_y);
        push_i32(&mut data, record.crop_width);
        push_i32(&mut data, record.crop_height);
        push_u16(&mut data, record.transform);
        push_u16(&mut data, record.presentation_bits);
    }
    Ok(data)
}

pub fn decode_wm_v1_projection_placement_records(
    data: &[u8],
    item_count: u32,
) -> Result<Vec<WmV1ProjectionPlacementRecord>, BinaryCodecError> {
    let count = item_count as usize;
    if count > 1024 {
        return Err(BinaryCodecError::CountTooLarge { count, max: 1024 });
    }
    let expected = count
        .checked_mul(60)
        .ok_or(BinaryCodecError::CountTooLarge { count, max: 1024 })?;
    if data.len() < expected {
        return Err(BinaryCodecError::Truncated);
    }
    if data.len() > expected {
        return Err(BinaryCodecError::TrailingBytes(data.len() - expected));
    }
    let mut cursor = Cursor::new(data);
    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let surface_index = cursor.u32()?;
        let surface_generation = cursor.u32()?;
        let state_generation = cursor.u64()?;
        let x = cursor.i32()?;
        let y = cursor.i32()?;
        let width = cursor.i32()?;
        let height = cursor.i32()?;
        let requested_width = cursor.i32()?;
        let requested_height = cursor.i32()?;
        let crop_x = cursor.i32()?;
        let crop_y = cursor.i32()?;
        let crop_width = cursor.i32()?;
        let crop_height = cursor.i32()?;
        let transform = cursor.u16()?;
        let presentation_bits = cursor.u16()?;
        records.push(WmV1ProjectionPlacementRecord {
            surface_index,
            surface_generation,
            state_generation,
            x,
            y,
            width,
            height,
            requested_width,
            requested_height,
            crop_x,
            crop_y,
            crop_width,
            crop_height,
            transform,
            presentation_bits,
        });
    }
    cursor.finish()?;
    Ok(records)
}

pub const PROJECTION_INDICATOR_RECORD_KIND: u16 = 3;
pub const PROJECTION_INDICATOR_RECORD_SIZE: usize = 64;
pub const PROJECTION_INDICATOR_RECORD_MAX: usize = 256;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionIndicatorRecord {
    pub output: u64,
    pub slot: u32,
    pub indicator: u64,
    pub action: u64,
    pub state_bits: u16,
    pub label_len: u16,
    pub label: [u8; 32],
}

pub fn encode_wm_v1_projection_indicator_records(
    records: &[WmV1ProjectionIndicatorRecord],
) -> Result<Vec<u8>, BinaryCodecError> {
    if records.len() > 256 {
        return Err(BinaryCodecError::CountTooLarge {
            count: records.len(),
            max: 256,
        });
    }
    let mut data = Vec::with_capacity(records.len() * 64);
    for record in records {
        push_u64(&mut data, record.output);
        push_u32(&mut data, record.slot);
        push_u64(&mut data, record.indicator);
        push_u64(&mut data, record.action);
        push_u16(&mut data, record.state_bits);
        push_u16(&mut data, record.label_len);
        data.extend_from_slice(&record.label);
    }
    Ok(data)
}

pub fn decode_wm_v1_projection_indicator_records(
    data: &[u8],
    item_count: u32,
) -> Result<Vec<WmV1ProjectionIndicatorRecord>, BinaryCodecError> {
    let count = item_count as usize;
    if count > 256 {
        return Err(BinaryCodecError::CountTooLarge { count, max: 256 });
    }
    let expected = count
        .checked_mul(64)
        .ok_or(BinaryCodecError::CountTooLarge { count, max: 256 })?;
    if data.len() < expected {
        return Err(BinaryCodecError::Truncated);
    }
    if data.len() > expected {
        return Err(BinaryCodecError::TrailingBytes(data.len() - expected));
    }
    let mut cursor = Cursor::new(data);
    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let output = cursor.u64()?;
        let slot = cursor.u32()?;
        let indicator = cursor.u64()?;
        let action = cursor.u64()?;
        let state_bits = cursor.u16()?;
        let label_len = cursor.u16()?;
        let mut label = [0u8; 32];
        label.copy_from_slice(cursor.slice(32)?);
        records.push(WmV1ProjectionIndicatorRecord {
            output,
            slot,
            indicator,
            action,
            state_bits,
            label_len,
            label,
        });
    }
    cursor.finish()?;
    Ok(records)
}

pub const PROJECTION_OUTPUT_STATUS_RECORD_KIND: u16 = 4;
pub const PROJECTION_OUTPUT_STATUS_RECORD_SIZE: usize = 48;
pub const PROJECTION_OUTPUT_STATUS_RECORD_MAX: usize = 16;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WmV1ProjectionOutputStatusRecord {
    pub output: u64,
    pub focus_bits: u16,
    pub layout_len: u16,
    pub layout: [u8; 32],
}

pub fn encode_wm_v1_projection_output_status_records(
    records: &[WmV1ProjectionOutputStatusRecord],
) -> Result<Vec<u8>, BinaryCodecError> {
    if records.len() > 16 {
        return Err(BinaryCodecError::CountTooLarge {
            count: records.len(),
            max: 16,
        });
    }
    let mut data = Vec::with_capacity(records.len() * 48);
    for record in records {
        push_u64(&mut data, record.output);
        push_u16(&mut data, record.focus_bits);
        push_u16(&mut data, record.layout_len);
        push_u32(&mut data, 0);
        data.extend_from_slice(&record.layout);
    }
    Ok(data)
}

pub fn decode_wm_v1_projection_output_status_records(
    data: &[u8],
    item_count: u32,
) -> Result<Vec<WmV1ProjectionOutputStatusRecord>, BinaryCodecError> {
    let count = item_count as usize;
    if count > 16 {
        return Err(BinaryCodecError::CountTooLarge { count, max: 16 });
    }
    let expected = count
        .checked_mul(48)
        .ok_or(BinaryCodecError::CountTooLarge { count, max: 16 })?;
    if data.len() < expected {
        return Err(BinaryCodecError::Truncated);
    }
    if data.len() > expected {
        return Err(BinaryCodecError::TrailingBytes(data.len() - expected));
    }
    let mut cursor = Cursor::new(data);
    let mut records = Vec::with_capacity(count);
    for _ in 0..count {
        let output = cursor.u64()?;
        let focus_bits = cursor.u16()?;
        let layout_len = cursor.u16()?;
        let reserved = cursor.u32()?;
        if reserved != 0 {
            return Err(BinaryCodecError::ReservedNonZero(reserved));
        }
        let mut layout = [0u8; 32];
        layout.copy_from_slice(cursor.slice(32)?);
        records.push(WmV1ProjectionOutputStatusRecord {
            output,
            focus_bits,
            layout_len,
            layout,
        });
    }
    cursor.finish()?;
    Ok(records)
}
