use super::*;

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub(super) struct PhysicalInputRouteReport {
    /// What a full ingress queue cost this pass. Non-zero means the endpoint
    /// epoch must close, which is the barrier that replaces the records lost.
    pub(super) ingress_saturation: RoutedInputIngressSaturation,
    pub(super) events: usize,
    pub(super) wm_actions: Vec<WmActionId>,
    pub(super) policy_inputs: Vec<PhysicalPolicyInput>,
    pub(super) presentation_capacity_exceeded: bool,
    pub(super) launcher_events: Vec<sophia_engine::LauncherInputEvent>,
    pub(super) reference_operations: Vec<(sophia_protocol::OutputId,u64,sophia_protocol::ShellReferenceOperation)>,
    pub(super) chrome_activations: Vec<(sophia_protocol::OutputId, WmActionId)>,
    pub(super) content_activations: Vec<sophia_engine::PresentedContentTarget>,
    pub(super) content_dismissals: Vec<sophia_engine::PresentedContentDismissal>,
    pub(super) descriptor_activations: Vec<(sophia_protocol::ToplevelActionCapabilityRef, u64)>,
    pub(super) chrome_captures_started: usize,
    pub(super) chrome_actions_activated: usize,
    pub(super) chrome_captures_cancelled: usize,
    pub(super) chrome_events_consumed: usize,
    pub(super) wm_pointer_gestures: Vec<sophia_protocol::WmPointerGestureCompleted>,
    pub(super) wm_pointer_interactions: Vec<FloatingPointerPolicyInteraction>,
    pub(super) floating_outline: FloatingPointerOutlineUpdate,
    pub(super) keys_observed: usize,
    pub(super) keys_suppressed_no_focus: usize,
    pub(super) keys_suppressed_stale_focus: usize,
    pub(super) key_targets: Vec<SurfaceId>,
    pub(super) routed_key_presses: Vec<(u64, u64)>,
    pub(super) deferred_key_presses: Vec<(u64, u64)>,
    pub(super) pointer_buttons_observed: usize,
    pub(super) pointer_buttons_suppressed_no_target: usize,
    pub(super) pointer_buttons_suppressed_by_policy: usize,
    pub(super) pointer_buttons_routed: usize,
    pub(super) pointer_lease_waits: usize,
    pub(super) pointer_lease_rejections: usize,
    pub(super) pointer_button_targets: Vec<SurfaceId>,
    pub(super) pointer_focus_targets: Vec<SurfaceId>,
    pub(super) pointer_axes_observed: usize,
    pub(super) pointer_axes_routed: usize,
    pub(super) pointer_axis_targets: Vec<SurfaceId>,
    pub(super) keys_routed: usize,
    pub(super) pointer_events: usize,
    pub(super) pointer_routed: usize,
    pub(super) deliveries: Vec<XAuthorityInputDeliveryId>,
    pub(super) emergency_exit: bool,
    pub(super) return_suppressed: bool,
    pub(super) virtual_terminal: Option<u8>,
    pub(super) virtual_terminal_trigger_keycode: Option<u32>,
    pub(super) virtual_terminal_modifier_keycodes: [Option<u32>; 4],
    pub(super) virtual_terminal_modifier_releases: usize,
    pub(super) pointer_focus_handoff_expired: bool,
    pub(super) pointer_focus_handoff_stale_drops: usize,
    pub(super) pointer_focus_handoff_capacity_drops: usize,
    pub(super) pointer_focus_handoff_released: Option<(SurfaceId, usize)>,
    pub(super) keyboard_focus_handoff_expired: bool,
    pub(super) keyboard_focus_handoff_stale_drops: usize,
    pub(super) keyboard_focus_handoff_capacity_drops: usize,
    pub(super) keyboard_focus_handoff_released: Option<(SurfaceId, usize)>,
    pub(super) pointer_boundary_entries: Vec<(sophia_engine::PointerBoundaryContact, Option<usize>)>,
    pub(super) pointer_boundary_reversals: Vec<(sophia_engine::PointerBoundaryContact, Option<usize>)>,
    pub(super) pointer_output_transitions: Vec<(sophia_engine::PointerOutputTransition, bool)>,
    /// Devices that joined the seat on this pass.
    pub(super) devices_added: Vec<DeviceArrival>,
    /// Devices that left the seat on this pass, with what each released.
    pub(super) devices_removed: Vec<DeviceRemoval>,
    /// Devices a key was observed from on this pass, first key only.
    pub(super) devices_keyed: Vec<DeviceId>,
    /// Releases issued for departed devices' keys. Tracked apart from
    /// `deliveries`: these are releases the seat owes, so they extend the
    /// release barrier the way a flush does.
    pub(super) device_release_deliveries: Vec<XAuthorityInputDeliveryId>,
}
