use sophia_protocol::*;

fn hex(bytes: &str) -> Vec<u8> {
    bytes
        .as_bytes()
        .chunks_exact(2)
        .map(|pair| u8::from_str_radix(std::str::from_utf8(pair).unwrap(), 16).unwrap())
        .collect()
}

#[test]
fn neutral_profile_aliases_preserve_all_six_preexisting_golden_frames() {
    // This corpus predates the extraction. Its generated bytes are unchanged.
    let corpus = include_str!("../../../protocol/golden/sophia-wm-v1.frames");
    let digest = hex("00112233445566778899aabbccddeeff102132435465768798a9bacbdcedfe0f");
    let identity = PolicyProfileIdentity::new(9, 7, digest.try_into().unwrap()).unwrap();
    let command = PolicyProfileCommand {
        transaction: TransactionId::from_raw(72623859790382856),
        identity,
    };
    let completion = PolicyProfileCompletion {
        transaction: command.transaction,
        identity,
        outcome: PolicyProfileOutcome::Accepted,
    };
    let mut count = 0;
    for line in corpus.lines().filter(|line| line.starts_with("profile_")) {
        let fields = line.split('|').collect::<Vec<_>>();
        let expected = hex(fields[2]);
        let bytes = match fields[0] {
            "profile_prepare" => {
                assert_eq!(decode_wm_v1_profile_prepare(&expected).unwrap(), command);
                encode_wm_v1_profile_prepare(command).unwrap()
            }
            "profile_activate" => {
                assert_eq!(decode_wm_v1_profile_activate(&expected).unwrap(), command);
                encode_wm_v1_profile_activate(command).unwrap()
            }
            "profile_rollback" => {
                assert_eq!(decode_wm_v1_profile_rollback(&expected).unwrap(), command);
                encode_wm_v1_profile_rollback(command).unwrap()
            }
            "profile_prepared" => {
                assert_eq!(
                    decode_wm_v1_profile_prepared(&expected).unwrap(),
                    completion
                );
                encode_wm_v1_profile_prepared(completion).unwrap()
            }
            "profile_active" => {
                assert_eq!(decode_wm_v1_profile_active(&expected).unwrap(), completion);
                encode_wm_v1_profile_active(completion).unwrap()
            }
            "profile_rolled_back" => {
                assert_eq!(
                    decode_wm_v1_profile_rolled_back(&expected).unwrap(),
                    completion
                );
                encode_wm_v1_profile_rolled_back(completion).unwrap()
            }
            other => panic!("unexpected profile record {other}"),
        };
        assert_eq!(bytes, expected, "{}", fields[0]);
        count += 1;
    }
    assert_eq!(count, 6);
    let legacy: WmV1ProfileCommand = command;
    let neutral: PolicyProfileCommand = legacy;
    assert_eq!(neutral, command);
    assert_eq!(POLICY_PROFILE_DIGEST_BYTES, WM_V1_PROFILE_DIGEST_BYTES);
}

#[test]
fn neutral_profile_validation_preserves_exact_legacy_errors_and_precedence() {
    for (epoch, generation, digest, field) in [
        (0, 0, [0; 32], "connection_epoch"),
        (9, 0, [0; 32], "profile_generation"),
        (9, 7, [0; 32], "profile_digest"),
    ] {
        let expected = Err(IpcCodecError::InvalidProfileIdentity(field));
        assert_eq!(
            PolicyProfileIdentity::new(epoch, generation, digest),
            expected
        );
        assert_eq!(
            WmV1ProfileIdentity::new(epoch, generation, digest),
            expected
        );
    }
    for value in [0, 4, u16::MAX] {
        let expected = Err(IpcCodecError::InvalidEnum {
            field: "profile_outcome",
            value: u32::from(value),
        });
        assert_eq!(PolicyProfileOutcome::try_from(value), expected);
        assert_eq!(WmV1ProfileOutcome::try_from(value), expected);
    }
}
