#![cfg(test)]

use super::*;

pub(super) fn head(
    id: u32,
    output: u64,
    capabilities: crate::LibdrmNativePlaneFormatCapabilities,
) -> LiveProductionNativeHead {
    let size = sophia_protocol::Size {
        width: 640,
        height: 480,
    };
    let output = sophia_engine::HeadlessOutput {
        id: OutputId::from_raw(output),
        size,
        scale: 1,
    };
    LiveProductionNativeHead {
        head: sophia_engine::RenderHeadId::from_raw(u64::from(id)),
        enabled: true,
        group: 0,
        selection: crate::LibdrmNativePrimaryPlaneSelection::new(
            ::drm::control::from_u32(id).unwrap(),
            ::drm::control::from_u32(id + 100).unwrap(),
            ::drm::control::from_u32(id + 200).unwrap(),
            size,
            None,
        ),
        format_capabilities: capabilities,
        scale: 1,
        refresh_millihz: 60_000,
        transform: sophia_protocol::OutputTransform::Normal,
        mapping: sophia_protocol::OutputHeadMapping::Fit,
        vrr: sophia_protocol::OutputVrrPolicy::Disabled,
        pending_callback: None,
        completion_mode: LiveProductionKmsCompletionMode::PageFlipPreferred,
        completion_fence_status: crate::LibdrmNativeCompletionFenceStatus::Unsupported,
        out_fence_retirements: 0,
        late_page_flip_events: 0,
        completion_fence_errors: 0,
        output,
        target_generation: 1,
        submitted_at: None,
        submitted_clock_source: None,
        submitted_ust_usec: None,
        pending_nonzero_pixel_bytes: 0,
        last_checksum: 0,
        submitted_checksum: None,
        submitted_sequence: None,
        pending_content: None,
        rendering_content: None,
        submitted_content: None,
        submitted_direct: false,
        layout_witness: layout_retirement::NativeLayoutWitnessState::default(),
        presented_direct: false,
        presented_content: None,
        presented_logical_checksum: 0,
        presented_submissions: 0,
        service_skew_baseline: None,
        presented_submission_ust_usec: 0,
        presented_page_flip_ust_usec: 0,
        presented_completion_timestamp: None,
        presented_submit_to_page_flip: Duration::ZERO,
        submissions: 0,
        retirements: 0,
        callback_accepted: 0,
        initial_modeset_submission: None,
        nonzero_exports: 0,
        last_submit_report: None,
        pending_cursor: None,
        pending_cursor_since: None,
        committed_cursor: None,
        cursor_properties: None,
        prepared_cursor_ride: None,
        scanout_custody: crate::PersistentScanoutCustody::default(),
        displayed_group_frame: None,
        prepared_scanout: None,
        prepared_group_frame: None,
        prepared_worker_was_in_flight: false,
        scanout_in_flight_ticks: 0,
        last_callback_serial: None,
        submitted_group_frame: None,
        output_frames: OutputFramePresentationState::new(output).unwrap(),
    }
}
