package shelloracle

func (r *runner) catalogScenario() {
	s := r.connect("dock", 4096)
	defer s.close()
	roleNegotiate(s, 8, 0x11a2, 0x11a2)
	r.check(85, true)
	s.phase("publish")
	a := announced(s, 3, 3)
	qid := s.w.file(10, 0, "catalog")
	old := s.object(10)
	need(qid == u64(a.body, 16), "catalog qid")
	r.check(86, u16(old.body, 26) == 1 && u16(old.body, 24) == 3 && string(roleText(old.body[428:688], 256)) == "registered:app1")
	s.w.walk(11, "catalog")
	need(errno(s.w.open(11, 0)) == 16, "catalog second pin")
	s.w.clunk(11)
	s.phase("republish")
	a = announced(s, 3, 4)
	r.check(87, identical(old.bytes, s.object(10).bytes))
	s.w.clunk(10)
	fresh := s.w.file(10, 0, "catalog")
	current := s.object(10)
	s.w.clunk(10)
	need(fresh != qid && fresh == u64(a.body, 16) && u64(current.body, 16) == 4, "fresh catalog")
	s.phase("maximum")
	maximum := roleObject(s, 3, 5)
	need(u16(maximum.body, 24) == 4096, "maximum catalog rows")
	s.phase("compact")
	roleObject(s, 3, 6)
	r.check(88, true)
	roleAllocation(s, false)
	r.check(89, true)
	smallResource(s)
	initialPermit := rolePermit(s, 1)
	r.check(90, true)
	generation := r.roleCandidateControls(s, false, 6, initialPermit)
	r.roleFatal("dock-permit-revoked", false)
	permit := rolePermit(s, 100)
	s.phase("hold-candidates")
	id := s.submit(270, roleCandidate(false, permit, generation, 6, 1))
	s.ack(s.custody(id, 270))
	s.noEvents()
	r.check(91, true)
	s.phase("release-candidates")
	prepared := roleOutcome(s, generation, 1, 0)
	presented := rolePresent(s, generation, false)
	r.check(92, presented.sequence > prepared.sequence)
	s.phase("action")
	action := s.expect(37)
	s.ack(action)
	s.phase("hold-activation")
	b := catalogActivateBody(action, 800, 6)
	id = s.submit(271, b)
	s.ack(s.custody(id, 271))
	s.noEvents()
	r.check(93, true)
	s.phase("release-activation")
	e := s.expect(44)
	r.check(94, identical(e.body[:128], b) && u16(e.body, 128) == 1 && u16(e.body, 130) == 0)
	s.ack(e)
	for i := 0; i < 2; i++ {
		s.phase("action")
		action = s.expect(37)
		s.ack(action)
		b = catalogActivateBody(action, 801+uint64(i), 6)
		if i == 0 {
			p64(b, 120, 3)
		} else {
			p64(b, 96, 4096)
		}
		id = s.submit(271, b)
		s.custody(id, 271)
		e = s.expect(44)
		r.check(95+i, identical(e.body[:128], b) && u16(e.body, 128) == 2 && u16(e.body, 130) == 0)
		s.ack(e)
	}
	s.phase("one-admission")
}
